### PR TITLE
Using OkHttpClient as default Http Client.

### PR DESCRIPTION
**Pull request by canyapan**
Classes for SSL/TLS connection are removed because OkHttpClient supports SSL as default.

A truststore can be loaded in case of a self signed certificate is used in server side.

Here is android example for custom truststore

KeyStore trustStore = KeyStore.getInstance("BKS");
InputStream trustStoreStream = null;
try {
    trustStoreStream = context.getResources().openRawResource(R.raw.truststore);
    trustStore.load(trustStoreStream, null);
} finally {
    if (null != trustStoreStream) {
        trustStoreStream.close();
    }
}

TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
trustManagerFactory.init(trustStore);

KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
keyManagerFactory.init(trustStore, null);

SSLContext sslContext = SSLContext.getInstance("TLS");
sslContext.init(keyManagerFactory.getKeyManagers(), trustManagerFactory.getTrustManagers(), null);

SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();

OkHttpClient client = new OkHttpClient.Builder()
        .sslSocketFactory(sslSocketFactory)
        .connectTimeout(10L, TimeUnit.SECONDS)
        .build();

### CODE REVIEW

**Comment by canyapan** [comment]
I know that there are a lot of changes. But they were necessary to support okhttp as default. As the user point of view it works the same except new okhttp dependency,
compile 'com.squareup.okhttp3:okhttp:3.9.1'
ntlm authentication requires jcifs as before,
compile 'jcifs:jcifs:1.3.17'

**Comment by canyapan** [comment]
Tests fail because of URLs are wrong. But, I am not sure, how they were passing with invalid URLs before.

**Comment by canyapan** [comment]
I think this was a bad idea.

**Comment by mosabua** [comment]
I think we should leave the default and just make the necessary adjustments in the OKHTTP related classes. Switching the default would also mess up too many existing apps and users on older phones.

**Comment by canyapan** [comment]
I know, thats why I took it back. But what do you think about opening a new module with better support for android projects without touching base or the other modules? It will only depend on the base module.

Of course It will be a new API and people will need to work in order to use it. But It opens a lot of possibilities too. 

OkHttp already supports a lot of features you implemented like SSL/TLS, gzip and keep alive. It brings a great API to add authenticators and interceptors.

Also, NTLM module cannot be supported directly to the current state. Because, it requires a resend request after first HTTP 401 which returns a key. But it cannot be done because there is a streaming request here. Streams cannot be repeated with OkHttp. Streaming must be changed by adding already created byte data to the request, which okhttp supports better.

I have already implemented a version. But I cannot commit it from this device. I can commit it on monday, if you would like to see.

**Comment by mosabua** [comment]
I am more than happy to have a closer look and pull it in and keep releasing with the new module. Wanna send a PR?

**Pull request closed without merging**
