### PR TITLE
Fixed Soap12 missing action on Content-Type header

### PR DESCRIPTION
**Pull request by gmazzo**
Hi, I was trying to use it against a Soap12 endpoints. Using SoapUI I've noticed the action was missing on the Content-Type header.

### CODE REVIEW

**Comment by robocik** [comment]
Looks good for me. For soap 1.2 action header should be added to Content-Type.
One question. You have added replace some characters. How do you know that is needed?

**Comment by gmazzo** [comment]
That's just in case the user sets the Action with quotes already set in the string. For example, the actions "someAction" and "\"someAction\"" will be the same.

**Comment by robocik** [comment]
Sounds good! Thanks for your pull request :)

**Comment by gmazzo** [comment]
Thanks to you!

Two cents:
1) I've noted you are pushing to sonatype, but the artifact is not in maven central. I've managed to include your release repo on my project, but you can publish it will make things a lot more easy to others devs.
2) I've also made a JsoupHttpTransportSE which parses the response into a Jsoup document instead a SoapObject. Jsoup is a library for querying HTML or XML documents in a jQuery style (CSS selectors).
3) I've run into issues with ProGuard after including the Android module. I've fixed them by making excluding the dependency on xpp3 and making the one of okhttp optional.

I'm going to push some additional requests

**Pull request closed without merging**
